# This file was generated by Kung github.com/slphyx/Kung 
# Sompob Saralamba <saralamba@gmail.com>
install.packages("shiny")

shinyUI(

  pageWithSidebar(

    # title
    headerPanel("Model Fitting on Tomato Flu outbreak"),

    # Sidebar with sliders
    sidebarPanel(
      

sliderInput("R0","R0", min = 1,max = 10,step = 0.01,value = 1),
sliderInput("gamma","gamma: rate of recovery = 1/(average duration of infection)", min = 1/10,max = 1/7,step = 0.001,value = 1/10),
sliderInput("week_interv","week_interv: weeks after first case when the intervention starts", min = 13,max = 53,step = 0.01,value = 13),
sliderInput("iso_perc_i","iso_perc_i: proportion of infected population which isolate themself during infected period", min = 0,max = 1,step = 0.01,value = 0),
sliderInput("iso_com","iso_com: average completeness of home isolation", min = 0,max = 1,step = 0.01,value = 1),
hr(),
actionButton('optimize','Do the Optimization')



      #add the quote
      , br(), hr(),
      tags$p("Everything organic and natural is good - ignoring the fact that organic natural substances include arsenic and poo and crocodiles. And everything chemical is bad, ignoring the fact that... everything is chemicals._(Tim Minchin)")
    ),


    # Show the plot 
    mainPanel(
      plotOutput("graphs")
    )
  )
)

